/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author b.dasilva
 */
public class Inscription extends javax.swing.JDialog {

    String urlPilote = "com.mysql.jdbc.Driver";
    String urlBaseDonnees = "jdbc:mysql://localhost:3333/gsbperso";
    private InterfaceGraphique fenetre;
    private Object requete;

    /**
     * Creates new form Connexion
     */
    public Inscription(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //modal==true signifie que l'on ne peut pas revenir 
        //sur la precedente fenêtre dans fermer connexion
        this.setModal(true);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre = (InterfaceGraphique) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAdresse = new javax.swing.JTextField();
        jLabelCP = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        jLabelVille = new javax.swing.JLabel();
        jTextFieldVille = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        jTextFieldMail = new javax.swing.JTextField();
        jLabelMobile = new javax.swing.JLabel();
        jTextFieldMobile = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jTextFieldSiteWeb = new javax.swing.JTextField();
        jTextFieldIdentifiant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelPromotion = new javax.swing.JLabel();
        jLabelIdentifiant = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldMDP = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSortiePromo = new javax.swing.JTextField();
        jButtonRempAuto = new javax.swing.JButton();
        jButtonInscrire = new javax.swing.JButton();
        jTextFieldEntreePromo = new javax.swing.JTextField();
        jLabelRole = new javax.swing.JLabel();
        jComboBoxUnRole = new javax.swing.JComboBox<>();
        jLabelPosition = new javax.swing.JLabel();
        jComboBoxUnePosition = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inscription");

        jLabelNom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNom.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Prénom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Adresse");

        jLabelCP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCP.setText("Code Postal");

        jLabelVille.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelVille.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVille.setText("Ville");

        jLabelMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMail.setText("Mail");

        jLabelMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMobile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMobile.setText("Mobile");

        jLabelTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTel.setText("Telephone");

        jTextFieldSiteWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSiteWebActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Site web");

        jLabelPromotion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPromotion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPromotion.setText("Entrée promotion");

        jLabelIdentifiant.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIdentifiant.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelIdentifiant.setText("Identifiant");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mot de passe");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Sortie promotion");

        jButtonRempAuto.setText("Remplisssage Automatique");
        jButtonRempAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRempAutoActionPerformed(evt);
            }
        });

        jButtonInscrire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonInscrire.setText("S'inscrire");
        jButtonInscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscrireActionPerformed(evt);
            }
        });

        jTextFieldEntreePromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEntreePromoActionPerformed(evt);
            }
        });

        jLabelRole.setText("Role");

        jComboBoxUnRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBoxUnRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnRoleActionPerformed(evt);
            }
        });

        jLabelPosition.setText("Position");

        jComboBoxUnePosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNom)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVille, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldSortiePromo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMobile, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldVille, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSiteWeb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldMDP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jComboBoxUnRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelCP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelPromotion)
                                            .addComponent(jLabelIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelRole))
                                        .addGap(13, 13, 13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldPrenom)
                                        .addComponent(jTextFieldCP)
                                        .addComponent(jTextFieldMail))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldEntreePromo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButtonRempAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabelPosition)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxUnePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCP)
                            .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPromotion)
                            .addComponent(jTextFieldEntreePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIdentifiant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRole)
                            .addComponent(jComboBoxUnRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNom)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVille))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMobile)
                            .addComponent(jTextFieldMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldSiteWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldSortiePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jPasswordFieldMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosition)
                    .addComponent(jComboBoxUnePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInscrire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRempAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSiteWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSiteWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSiteWebActionPerformed

    private void jButtonInscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscrireActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNom.getText().length() == 0 || jTextFieldAdresse.getText().length() == 0 || jTextFieldVille.getText().length() == 0 || jTextFieldMobile.getText().length() == 0 || jTextFieldSortiePromo.getText().length() == 0 || jPasswordFieldMDP.getText().length() == 0 || jTextFieldPrenom.getText().length() == 0 || jTextFieldCP.getText().length() == 0 || jTextFieldMail.getText().length() == 0 || jTextFieldTel.getText().length() == 0 || jTextFieldSiteWeb.getText().length() == 0 || jTextFieldIdentifiant.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Erreur de saisie, un des champs n'est pas renseignés.");

            this.fenetre.deconnecte();
        } else {

            try {
                //interrogation de la BD pour savoir si l'identifiant/mot de passe est correct
                //instanciation de la classe Driver du paquetage jdbc de mysql
                Class.forName(urlPilote);
                System.out.println("Chargement du pilote réussie");
                //Chaine de connexion (prise dans l'onglet services)

                //etablissement de la connexion
                Connection monInscription = (Connection) DriverManager.getConnection(urlBaseDonnees, "gsbperso", "sio");
                System.out.println("Connexion a la BDD réussie");

                Statement requete = monInscription.createStatement();
                String nom = jTextFieldNom.getText();
                String prenom = jTextFieldPrenom.getText();
                String adresse_rue = jTextFieldAdresse.getText();
                String adresse_cp = jTextFieldCP.getText();
                String adresse_ville = jTextFieldVille.getText();
                String tel_personnel = jTextFieldMobile.getText();
                String tel_professionnel = jTextFieldTel.getText();
                String mail = jTextFieldMail.getText();
                String site_web = jTextFieldSiteWeb.getText();
                String annee_entree_promotion = jTextFieldSiteWeb.getText();
                String annee_sortie_promotion = jTextFieldSortiePromo.getText();
                String identifiant = jTextFieldIdentifiant.getText();
                String mot_de_passe = jPasswordFieldMDP.getText();
                int id_role = jComboBoxUnRole.getSelectedIndex()+1;
                int id_cadre = jComboBoxUnePosition.getSelectedIndex()+1;
                
                try {
                    mot_de_passe = Outils.md5(mot_de_passe);
                } catch (Exception e) {
                }
                //application du cryptage md5 au mdp
                // ici on appelle md5 membre static de la classe outils
                
                //requete
                System.out.println("INSERT INTO utilisateurs (nom,prenom,adresse_rue,adresse_cp,adresse_ville,tel_personnel,tel_professionnel,mail,site_web,annee_entree_promotion,annee_sortie_promotion,identifiant,mot_de_passe,id_role,id_cadre)" + "VALUES('" + nom + "','" + prenom + "','" + adresse_rue + "','" + adresse_cp + "','" + adresse_ville + "','" + mail + "','" + tel_personnel + "','" + tel_professionnel + "','" + site_web + "','" + annee_entree_promotion + "','" + annee_sortie_promotion + "','" + identifiant + "','" + mot_de_passe + "','" + id_role + "','" + id_cadre + "'");
                Integer lignesRetournees = requete.executeUpdate("INSERT INTO utilisateurs (nom,prenom,adresse_rue,adresse_cp,adresse_ville,tel_personnel,tel_professionnel,mail,site_web,annee_entree_promotion,annee_sortie_promotion,identifiant,mot_de_passe,id_role,id_cadre)" + "VALUES('" + nom + "','" + prenom + "','" + adresse_rue + "','" + adresse_cp + "','" + adresse_ville + "','" + mail + "','" + tel_personnel + "','" + tel_professionnel + "','" + site_web + "','" + annee_entree_promotion + "','" + annee_sortie_promotion + "','" + identifiant + "','" + mot_de_passe + "','" + id_role + "','" +id_cadre +"');");
                if (lignesRetournees == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Inscription réussie");
                }

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(rootPane, "Classe de connexion mysql non trouvee..." + ex.toString());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "SQL exception ... " + ex.toString());

            }

        }
    }//GEN-LAST:event_jButtonInscrireActionPerformed

    private void jButtonRempAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRempAutoActionPerformed
        // TODO add your handling code here:
        jTextFieldNom.setText("Chavernac");
        jTextFieldPrenom.setText("Paul");
        jTextFieldAdresse.setText("9 chemin de la prade");
        jTextFieldCP.setText("34 370");
        jTextFieldVille.setText("Cazouls les Béziers");
        jTextFieldMail.setText("chavernac.paul.lurcat@gmail.com");
        jTextFieldMobile.setText("0768162317");
        jTextFieldTel.setText("0467935075");
        jTextFieldSiteWeb.setText("Aucun");
        jTextFieldEntreePromo.setText("2016");
        jTextFieldSortiePromo.setText("2018");
        jTextFieldIdentifiant.setText("pchav9");
        jPasswordFieldMDP.setText("harry97434");
    }//GEN-LAST:event_jButtonRempAutoActionPerformed

    private void jTextFieldEntreePromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEntreePromoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEntreePromoActionPerformed

    private void jComboBoxUnRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inscription dialog = new Inscription(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscrire;
    private javax.swing.JButton jButtonRempAuto;
    private javax.swing.JComboBox<String> jComboBoxUnRole;
    private javax.swing.JComboBox<String> jComboBoxUnePosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCP;
    private javax.swing.JLabel jLabelIdentifiant;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMobile;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelPromotion;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JPasswordField jPasswordFieldMDP;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldEntreePromo;
    private javax.swing.JTextField jTextFieldIdentifiant;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSiteWeb;
    private javax.swing.JTextField jTextFieldSortiePromo;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables

}
