/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_etudiants;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maiwenn
 */
public class Promouvoir extends javax.swing.JDialog {

    private InterfaceGraphique fenetre;
    String urlPilote = "com.mysql.jdbc.Driver";
    String urlBaseDonnees = "jdbc:mysql://localhost:3333/gsbperso";

    /**
     * Creates new form Promouvoir_employe
     */
    public Promouvoir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //positionnement au milieu de la fenetre parente
        this.setLocationRelativeTo(parent);
        //modal==true signifie que l'on ne peut pas revenir 
        //sur la precedente fenêtre dans fermer connexion
        this.setModal(true);
        //on stocke dans this.fenetre la référence vers la fenetre parente
        this.fenetre = (InterfaceGraphique) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPromouvoirEmploye = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldUnNom = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        jTextFieldUnPrenom = new javax.swing.JTextField();
        jComboBoxChoixRole = new javax.swing.JComboBox<>();
        jButtonEnregistre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelPromouvoirEmploye.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPromouvoirEmploye.setText("Promouvoir un Employé");

        jLabelNom.setText("Nom");

        jLabelPrenom.setText("Prenom");

        jComboBoxChoixRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxChoixRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Responsable" }));
        jComboBoxChoixRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixRoleActionPerformed(evt);
            }
        });

        jButtonEnregistre.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonEnregistre.setText("Enregistrer");
        jButtonEnregistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabelPromouvoirEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUnNom, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jLabelPrenom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUnPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jComboBoxChoixRole, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonEnregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelPromouvoirEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldUnNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom)
                    .addComponent(jTextFieldUnPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addComponent(jComboBoxChoixRole, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButtonEnregistre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnregistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistreActionPerformed
        // TODO add your handling code here:
        if (jTextFieldUnNom.getText().length() == 0 || jTextFieldUnPrenom.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Erreur, un des champs n'a pas été rempli");
            this.fenetre.deconnecte();
        } else {
            try {
                Class.forName(urlPilote);
                System.out.println("Chargement du pilote réussie");
                //Chaine de connexion (prise dans l'onglet services)

                //etablissement de la connexion
                Connection monInscription = (Connection) DriverManager.getConnection(urlBaseDonnees, "gsbperso", "sio");
                System.out.println("Connexion a la BDD réussie");

                Statement requete = monInscription.createStatement();
                int unRole = jComboBoxChoixRole.getSelectedIndex() + 2; 
                String nom = jTextFieldUnNom.getText();
                String prenom = jTextFieldUnPrenom.getText();
                Integer lignesRetournees = requete.executeUpdate("UPDATE employe SET id_role='" + unRole + "' WHERE nom= '" + nom + "' AND prenom '" + prenom +"'");
                if (lignesRetournees == 1) {
                    JOptionPane.showMessageDialog(this, "Felicitations, votre employé a été promu en responsable");
                    this.setVisible(false);
                    this.fenetre.directeur();
                }else{
                    JOptionPane.showMessageDialog(rootPane, "champs non remplis");
                };
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Promouvoir.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Promouvoir.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonEnregistreActionPerformed

    private void jComboBoxChoixRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxChoixRoleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promouvoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promouvoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promouvoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promouvoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Promouvoir dialog = new Promouvoir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnregistre;
    private javax.swing.JComboBox<String> jComboBoxChoixRole;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPromouvoirEmploye;
    private javax.swing.JTextField jTextFieldUnNom;
    private javax.swing.JTextField jTextFieldUnPrenom;
    // End of variables declaration//GEN-END:variables
}
